### ISSUE TITLE
Fix elasticsearch image build

### ISSUE THREAD

**Issue by jakolehm** [qtcloudservices/mdb-dockerfiles#1]

**Comment by jnummelin** [comment]
https://github.com/jprante/elasticsearch-jdbc/issues/469

1.3.4.7 might work, let's see if the guy responds

**Comment by jnummelin** [comment]
Other option is to grab the plugin version from existing image and put it available on S3 or git.

Just wondering has these really been used at all, since the JDBC driver probably do not work at all:
https://github.com/qtcloudservices/mdb-dockerfiles/blob/master/elasticsearch/1.3/Dockerfile#L17-18
There's a typo in the path where the drivers are copied. :)

**Comment by jakolehm** [comment]
Interesting.. we should fix those paths :)
